-- Sequence Items
CREATE TABLE IF NOT EXISTS `#__jex_sequences` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `catid` INT UNSIGNED NOT NULL DEFAULT 0,
    `title` VARCHAR(255) NULL,
    `alias` VARCHAR(255) NOT NULL DEFAULT '',
    `subtitle` VARCHAR(255) NULL,
    `heading` VARCHAR(255) NOT NULL,
    `subheading` VARCHAR(255) NULL,
    `header` TEXT NULL,
    `body` TEXT NULL,
    `footer` TEXT NULL,
    `images` TEXT NOT NULL,
    `links` TEXT NOT NULL,
    `timeline` TINYINT(1) NOT NULL DEFAULT 0,
    `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `access` INT UNSIGNED NOT NULL DEFAULT 1,
    `language` CHAR(7) NOT NULL DEFAULT '*',
    `published` TINYINT(1) NOT NULL DEFAULT 1,
    `note` VARCHAR(255) NULL,
    `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
    `modified` DATETIME DEFAULT NULL,
    `modified_by` INT UNSIGNED DEFAULT NULL,
    `ordering` INT UNSIGNED NOT NULL DEFAULT 0,
    `params` TEXT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_date` (`date`),
    KEY `idx_published` (`published`),
    KEY `idx_language` (`language`),
    KEY `idx_access` (`access`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

-- Carousel Items
CREATE TABLE IF NOT EXISTS `#__jex_carousels` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `catid` INT UNSIGNED NOT NULL DEFAULT 0,
    `title` VARCHAR(255) NULL,
    `subtitle` VARCHAR(255) NULL,
    `header` TEXT NULL,
    `body` TEXT NULL,
    `footer` TEXT NULL,
    `images` TEXT NOT NULL,
    `links` TEXT NOT NULL,
    `access` INT UNSIGNED NOT NULL DEFAULT 1,
    `language` CHAR(7) NOT NULL DEFAULT '*',
    `published` TINYINT(1) NOT NULL DEFAULT 1,
    `note` VARCHAR(255) NULL,
    `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
    `modified` DATETIME DEFAULT NULL,
    `modified_by` INT UNSIGNED DEFAULT NULL,
    `ordering` INT UNSIGNED NOT NULL DEFAULT 0,
    `params` TEXT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_published` (`published`),
    KEY `idx_language` (`language`),
    KEY `idx_access` (`access`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

-- Testimonial Items
CREATE TABLE IF NOT EXISTS `#__jex_testimonials` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `catid` INT UNSIGNED NOT NULL DEFAULT 0,
    `title` VARCHAR(255) NULL,
    `header` TEXT NULL,
    `body` TEXT NOT NULL,
    `footer` TEXT NULL,
    `author` VARCHAR(255) NOT NULL,
    `about` TEXT NULL,
    `images` TEXT NOT NULL,
    `links` TEXT NOT NULL,
    `access` INT UNSIGNED NOT NULL DEFAULT 1,
    `language` CHAR(7) NOT NULL DEFAULT '*',
    `published` TINYINT(1) NOT NULL DEFAULT 1,
    `note` VARCHAR(255) NULL,
    `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
    `modified` DATETIME DEFAULT NULL,
    `modified_by` INT UNSIGNED DEFAULT NULL,
    `ordering` INT UNSIGNED NOT NULL DEFAULT 0,
    `params` TEXT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_published` (`published`),
    KEY `idx_language` (`language`),
    KEY `idx_access` (`access`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

-- Quote Items
CREATE TABLE IF NOT EXISTS `#__jex_quotes` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `catid` INT UNSIGNED NOT NULL DEFAULT 0,
    `title` VARCHAR(255) NULL,
    `header` TEXT NULL,
    `body` TEXT NOT NULL,
    `footer` TEXT NULL,
    `author` VARCHAR(255) NOT NULL,
    `about` TEXT NULL,
    `images` TEXT NOT NULL,
    `links` TEXT NOT NULL,
    `access` INT UNSIGNED NOT NULL DEFAULT 1,
    `language` CHAR(7) NOT NULL DEFAULT '*',
    `published` TINYINT(1) NOT NULL DEFAULT 1,
    `note` VARCHAR(255) NULL,
    `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
    `modified` DATETIME DEFAULT NULL,
    `modified_by` INT UNSIGNED DEFAULT NULL,
    `ordering` INT UNSIGNED NOT NULL DEFAULT 0,
    `params` TEXT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_published` (`published`),
    KEY `idx_language` (`language`),
    KEY `idx_access` (`access`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;